port: 7890
socks-port: 7891
mixed-port: 7892
mode: rule
log-level: info
external-controller: 0.0.0.0:9090


dns:
  enable: true
  ipv6: true
  listen: 0.0.0.0:53
  default-nameserver:
    - 223.5.5.5
    - 119.29.29.29
  enhanced-mode: redir-host
  prefer-h3: true
  nameserver-policy:
    geosite:cn,apple-cn,microsoft@cn:
      - https://dns.alidns.com/dns-query
      - https://doh.pub/dns-query
  nameserver:
    - https://1.0.0.1/dns-query
    - tls://8.8.4.4:853
  proxy-server-nameserver:
    - https://dns.alidns.com/dns-query
    - https://doh.pub/dns-query


sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
  force-domain:
    - "+.v2ex.com"
    - "+.netflix.com"
    - "+.nflxvideo.net"
    - "+.amazonaws.com"
    - "+.media.dssott.com"
  skip-domain:
    - "+.apple.com"
    - Mijia Cloud
    - dlg.io.mi.com
  sniff:
    TLS:
      ports:
        - 443
        - 8443
    HTTP:
      ports:
        - 80
        - 8080-8880
      override-destination: true
    QUIC:
      ports:
        - 443
        - 8443


geodata-mode: true
geox-url:
  geoip: "https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip-lite.dat"
  geosite: "https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.dat"
  mmdb: "https://mirror.ghproxy.com/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/country-lite.mmdb"


proxies:


proxy-providers:
  CNIX:
    type: http
    path: ./profiles/CNIX.yaml
    url:
    interval: 86400
    health-check:
      enable: true
      url: https://www.gstatic.com/generate_204
      interval: 300
    exclude-filter: "到期|剩余流量|时间|官网|产品|购买|漏洞|备用|客服|禁止"


proxy-groups:
  - name: 🚀 节点选择
    type: select
    proxies:
      - 🔃 自动选择
      - DIRECT
    use:
      - CNIX

  - name: 🔃 自动选择
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 300
    tolerance: 50
    use: 
      - CNIX

  - name: 💻 微软服务
    type: select
    proxies:
      - DIRECT
      - 🚀 节点选择

  - name: 🍎 苹果服务
    type: select
    proxies:
      - DIRECT
      - 🚀 节点选择

  - name: 🍎 苹果解锁
    type: select
    proxies:
      - DIRECT
      - 🚀 节点选择
      - 🎥 媒体解锁

  - name: 💬 AI服务
    type: select
    proxies:
      - 🚀 节点选择
      - DIRECT
    use:
      - CNIX
    filter: "美|US"

  - name: 🎥 媒体解锁
    type: select
    proxies:
      - 🚀 节点选择
      - DIRECT
    use:
      - CNIX
    filter: "NF|奈飞|Netflix|NETFLIX|HBO|Disney|迪士尼|动画疯|動畫瘋|美|US"

  - name: 🎮 游戏平台
    type: select
    proxies:
      - 🚀 节点选择
      - DIRECT  
    use:
      - CNIX
     
  - name: 🇺🇸 阿美莉卡
    type: select
    proxies:
    use:
      - CNIX
    filter: "美|US"

  - name: 📺 哔哩哔哩
    type: select
    proxies:
      - DIRECT
    use:
      - CNIX
    filter: "港|HK|Hong Kong|台|新北|彰化|TW|Taiwan"
  
  - name: 🛑 拦截防护
    type: select
    proxies:
      - REJECT
      - DIRECT

  - name: 🐟 漏网之鱼
    type: select
    proxies:
      - 🚀 节点选择
      - DIRECT

    
rules:
  # 自定义规则
  - RULE-SET,TopDirect,DIRECT

  # 拦截
  - GEOSITE,category-ads-all,REJECT
  
  # Bilibili
  - GEOSITE,bilibili,📺 哔哩哔哩
  # 国内网站
  - GEOSITE,cn,DIRECT
  - GEOSITE,googlefcm,DIRECT

  # AI服务
  - GEOSITE,openai,💬 AI服务
  - GEOSITE,bing@cn,DIRECT
  - GEOSITE,bing,💬 AI服务

  # 阿美莉卡
  - GEOSITE,paypal,🇺🇸 阿美莉卡
  - RULE-SET,USMobile,🇺🇸 阿美莉卡

  # 媒体解锁
  - GEOSITE,youtube,🎥 媒体解锁
  - GEOSITE,netflix,🎥 媒体解锁
  - GEOSITE,hbo,🎥 媒体解锁
  - GEOSITE,disney,🎥 媒体解锁
  - GEOSITE,spotify,🎥 媒体解锁
  - GEOSITE,bahamut,🎥 媒体解锁
  - GEOSITE,tiktok,🎥 媒体解锁
  
  # 游戏平台
  - GEOSITE,category-games@cn,DIRECT
  - GEOSITE,category-games,🎮 游戏平台

  # 苹果服务
  - RULE-SET,AppleUnlock,🍎 苹果解锁
  - GEOSITE,apple-cn,DIRECT
  - GEOSITE,apple,🍎 苹果服务

  # 微软服务
  - GEOSITE,github,🚀 节点选择
  - GEOSITE,microsoft@cn,DIRECT
  - GEOSITE,microsoft,💻 微软服务
  
  # 代理
  - GEOSITE,telegram,🚀 节点选择
  - GEOSITE,geolocation-!cn,🚀 节点选择

  # GEOIP规则
  - GEOIP,private,DIRECT,no-resolve
  - GEOIP,telegram,🚀 节点选择
  - GEOIP,netflix,🎥 媒体解锁
  - GEOIP,CN,DIRECT

  # 漏网之鱼
  - MATCH,🐟 漏网之鱼


rule-providers:
  TopDirect:
    type: http
    path: ./rulesets/TopDirect.txt
    url: "https://raw.githubusercontent.com/BlackPeton/SubConverterConfigs/main/rulesets/Direct.list"
    interval: 86400
    proxy: DIRECT
    behavior: classical
    format: text

  AppleUnlock:
    type: http
    path: ./rulesets/AppleUnlock.txt 
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/AppleTV/AppleTV.list"
    interval: 86400
    proxy: DIRECT
    behavior: classical
    format: text

  USMobile:
    type: http
    path: ./rulesets/USMobile.txt
    url: "https://raw.githubusercontent.com/BlackPeton/SubConverterConfigs/main/rulesets/USMobile.list"
    interval: 86400
    proxy: DIRECT
    behavior: classical
    format: text
